# This plotting code was generated by AI


import json
import numpy as np
import matplotlib.pyplot as plt
import os

plt.rcParams.update({
    "font.size": 14,        # base font size
    "axes.titlesize": 18,   # title
    "axes.labelsize": 16,   # x/y labels
    "xtick.labelsize": 14,  # tick labels
    "ytick.labelsize": 14,
    "legend.fontsize": 14
})

# ===== CONFIG =====
GRAPH_TYPE = "hist"   # "hist", "bar", "line"
BINS = 20


def load_path_lengths(filepath):
    with open(filepath, 'r') as f:
        data = json.load(f)

    path_lengths = data["results"]["path_lengths"]

    # Use termination.name as label
    label = data.get("termination", {}).get(
        "name",
        os.path.basename(filepath)
    )

    problem = data.get("problem", os.path.basename(filepath))

    return path_lengths, label, problem


def plot_data(filepaths, graph_type="hist"):
    series_data = []
    labels = []

    # Load all files
    for path in filepaths:
        path_lengths, label, problem = load_path_lengths(path)
        series_data.append(path_lengths)
        labels.append(label)

    plt.figure(figsize=(12, 6))

    if graph_type == "hist":
        # Create shared bins for fair comparison
        all_data = np.concatenate(series_data)
        bins = np.linspace(min(all_data), max(all_data), BINS)

        ax = plt.gca()
        colors = plt.rcParams['axes.prop_cycle'].by_key()['color']

        # Move legend slightly up on the right
        legend = ax.legend(loc='upper right')

        # Add info box below legend
        ax.text(
            0.98, 0.75,  # tweak Y if needed depending on legend size
            f"Bins: {len(bins)-1}\nRuns: 100",
            transform=ax.transAxes,
            fontsize=14,
            verticalalignment='top',
            horizontalalignment='right',
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.7)
        )

        for i, (data, label) in enumerate(zip(series_data, labels)):
            color = colors[i % len(colors)]

            # Filled histogram
            ax.hist(
                data,
                bins=bins,
                alpha=0.2,
                color=color,
                label=label
            )

            # Outline
            ax.hist(
                data,
                bins=bins,
                histtype='step',
                alpha=0.8,
                linewidth=1,
                color=color
            )

            # Mean line
            mean_val = np.mean(data)
            ax.axvline(
                mean_val,
                linestyle='--',
                linewidth=2,
                color=color
            )

            plt.xlabel("Path Length")
            plt.ylabel("Frequency")
            # plt.title("Histogram of Path Lengths (" + problem + ")")

    elif graph_type == "bar":
        min_len = min(len(s) for s in series_data)
        series_data = [s[:min_len] for s in series_data]

        x = np.arange(min_len)
        width = 0.8 / len(series_data)

        for i, (data, label) in enumerate(zip(series_data, labels)):
            offset = (i - len(series_data)/2) * width + width/2
            plt.bar(x + offset, data, width=width, label=label)

        plt.xlabel("Run Index")
        plt.ylabel("Path Length")
        plt.title("Bar Chart of Path Lengths")

    elif graph_type == "line":
        for data, label in zip(series_data, labels):
            plt.plot(data, label=label)

        plt.xlabel("Run Index")
        plt.ylabel("Path Length")
        plt.title("Line Plot of Path Lengths")

    else:
        raise ValueError(f"Unsupported graph type: {graph_type}")

    plt.legend()
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    files = [
        # "results/Ant system-eil51-2026-04-14-16-36-29.json",
        # "results/Ant system-eil51-2026-04-14-16-37-01.json",
        # "results/Ant system-eil51-2026-04-14-16-37-11.json"
        "results/Ant system-ch150-2026-04-13-00-12-50.json",
        "results/Ant system-ch150-2026-04-13-00-23-44.json",
        "results/Ant system-ch150-2026-04-13-00-50-59.json",
    ]

    plot_data(files, GRAPH_TYPE)